import { getUser } from "@/auth/auth-guard"
import AppProvider from "@/providers/app-provider"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { userId } = await getUser()
  return (
    <html lang="en">
      <AppProvider userId={userId}>
        <body className={inter.className}>
          <main className="flex h-screen items-center justify-center">
            {children}
          </main>
        </body>
      </AppProvider>
    </html>
  )
}
